/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlunoRouteImport } from './routes/aluno'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as ProfessorRouteImport } from './routes/professor'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as AlunoIndexRouteImport } from './routes/aluno.index'
import { Route as AlunoFaltasRouteImport } from './routes/aluno.faltas'
import { Route as AlunoHorariosRouteImport } from './routes/aluno.horarios'
import { Route as AlunoNotasRouteImport } from './routes/aluno.notas'
import { Route as AlunoNotificacoesRouteImport } from './routes/aluno.notificacoes'
import { Route as AlunoPropinasRouteImport } from './routes/aluno.propinas'
import { Route as AlunoRankingRouteImport } from './routes/aluno.ranking'
import { Route as AlunoTrocarSenhaRouteImport } from './routes/aluno.trocar-senha'
import { Route as ProfessorIndexRouteImport } from './routes/professor.index'
import { Route as ProfessorHorarioRouteImport } from './routes/professor.horario'
import { Route as ProfessorLancarNotasRouteImport } from './routes/professor.lancar-notas'
import { Route as ProfessorNotasRouteImport } from './routes/professor.notas'
import { Route as ProfessorPerfilRouteImport } from './routes/professor.perfil'
import { Route as ProfessorTurmasRouteImport } from './routes/professor.turmas'
import { Route as ProfessorTurmasTurmaIdRouteImport } from './routes/professor.turmas.$turmaId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunoRoute = AlunoRouteImport.update({
  id: '/aluno',
  path: '/aluno',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessorRoute = ProfessorRouteImport.update({
  id: '/professor',
  path: '/professor',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunoIndexRoute = AlunoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoFaltasRoute = AlunoFaltasRouteImport.update({
  id: '/faltas',
  path: '/faltas',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoHorariosRoute = AlunoHorariosRouteImport.update({
  id: '/horarios',
  path: '/horarios',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoNotasRoute = AlunoNotasRouteImport.update({
  id: '/notas',
  path: '/notas',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoNotificacoesRoute = AlunoNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoPropinasRoute = AlunoPropinasRouteImport.update({
  id: '/propinas',
  path: '/propinas',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoRankingRoute = AlunoRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoTrocarSenhaRoute = AlunoTrocarSenhaRouteImport.update({
  id: '/trocar-senha',
  path: '/trocar-senha',
  getParentRoute: () => AlunoRoute,
} as any)
const ProfessorIndexRoute = ProfessorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfessorRoute,
} as any)
const ProfessorHorarioRoute = ProfessorHorarioRouteImport.update({
  id: '/horario',
  path: '/horario',
  getParentRoute: () => ProfessorRoute,
} as any)
const ProfessorLancarNotasRoute = ProfessorLancarNotasRouteImport.update({
  id: '/lancar-notas',
  path: '/lancar-notas',
  getParentRoute: () => ProfessorRoute,
} as any)
const ProfessorNotasRoute = ProfessorNotasRouteImport.update({
  id: '/notas',
  path: '/notas',
  getParentRoute: () => ProfessorRoute,
} as any)
const ProfessorPerfilRoute = ProfessorPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => ProfessorRoute,
} as any)
const ProfessorTurmasRoute = ProfessorTurmasRouteImport.update({
  id: '/turmas',
  path: '/turmas',
  getParentRoute: () => ProfessorRoute,
} as any)
const ProfessorTurmasTurmaIdRoute = ProfessorTurmasTurmaIdRouteImport.update({
  id: '/$turmaId',
  path: '/$turmaId',
  getParentRoute: () => ProfessorTurmasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aluno': typeof AlunoRouteWithChildren
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/professor': typeof ProfessorRouteWithChildren
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/termos': typeof TermosRoute
  '/aluno/faltas': typeof AlunoFaltasRoute
  '/aluno/horarios': typeof AlunoHorariosRoute
  '/aluno/notas': typeof AlunoNotasRoute
  '/aluno/notificacoes': typeof AlunoNotificacoesRoute
  '/aluno/propinas': typeof AlunoPropinasRoute
  '/aluno/ranking': typeof AlunoRankingRoute
  '/aluno/trocar-senha': typeof AlunoTrocarSenhaRoute
  '/professor/horario': typeof ProfessorHorarioRoute
  '/professor/lancar-notas': typeof ProfessorLancarNotasRoute
  '/professor/notas': typeof ProfessorNotasRoute
  '/professor/perfil': typeof ProfessorPerfilRoute
  '/professor/turmas': typeof ProfessorTurmasRouteWithChildren
  '/aluno/': typeof AlunoIndexRoute
  '/professor/': typeof ProfessorIndexRoute
  '/professor/turmas/$turmaId': typeof ProfessorTurmasTurmaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/termos': typeof TermosRoute
  '/aluno/faltas': typeof AlunoFaltasRoute
  '/aluno/horarios': typeof AlunoHorariosRoute
  '/aluno/notas': typeof AlunoNotasRoute
  '/aluno/notificacoes': typeof AlunoNotificacoesRoute
  '/aluno/propinas': typeof AlunoPropinasRoute
  '/aluno/ranking': typeof AlunoRankingRoute
  '/aluno/trocar-senha': typeof AlunoTrocarSenhaRoute
  '/professor/horario': typeof ProfessorHorarioRoute
  '/professor/lancar-notas': typeof ProfessorLancarNotasRoute
  '/professor/notas': typeof ProfessorNotasRoute
  '/professor/perfil': typeof ProfessorPerfilRoute
  '/professor/turmas': typeof ProfessorTurmasRouteWithChildren
  '/aluno': typeof AlunoIndexRoute
  '/professor': typeof ProfessorIndexRoute
  '/professor/turmas/$turmaId': typeof ProfessorTurmasTurmaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aluno': typeof AlunoRouteWithChildren
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/professor': typeof ProfessorRouteWithChildren
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/termos': typeof TermosRoute
  '/aluno/faltas': typeof AlunoFaltasRoute
  '/aluno/horarios': typeof AlunoHorariosRoute
  '/aluno/notas': typeof AlunoNotasRoute
  '/aluno/notificacoes': typeof AlunoNotificacoesRoute
  '/aluno/propinas': typeof AlunoPropinasRoute
  '/aluno/ranking': typeof AlunoRankingRoute
  '/aluno/trocar-senha': typeof AlunoTrocarSenhaRoute
  '/professor/horario': typeof ProfessorHorarioRoute
  '/professor/lancar-notas': typeof ProfessorLancarNotasRoute
  '/professor/notas': typeof ProfessorNotasRoute
  '/professor/perfil': typeof ProfessorPerfilRoute
  '/professor/turmas': typeof ProfessorTurmasRouteWithChildren
  '/aluno/': typeof AlunoIndexRoute
  '/professor/': typeof ProfessorIndexRoute
  '/professor/turmas/$turmaId': typeof ProfessorTurmasTurmaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aluno'
    | '/login'
    | '/privacidade'
    | '/professor'
    | '/recuperar-senha'
    | '/termos'
    | '/aluno/faltas'
    | '/aluno/horarios'
    | '/aluno/notas'
    | '/aluno/notificacoes'
    | '/aluno/propinas'
    | '/aluno/ranking'
    | '/aluno/trocar-senha'
    | '/professor/horario'
    | '/professor/lancar-notas'
    | '/professor/notas'
    | '/professor/perfil'
    | '/professor/turmas'
    | '/aluno/'
    | '/professor/'
    | '/professor/turmas/$turmaId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/privacidade'
    | '/recuperar-senha'
    | '/termos'
    | '/aluno/faltas'
    | '/aluno/horarios'
    | '/aluno/notas'
    | '/aluno/notificacoes'
    | '/aluno/propinas'
    | '/aluno/ranking'
    | '/aluno/trocar-senha'
    | '/professor/horario'
    | '/professor/lancar-notas'
    | '/professor/notas'
    | '/professor/perfil'
    | '/professor/turmas'
    | '/aluno'
    | '/professor'
    | '/professor/turmas/$turmaId'
  id:
    | '__root__'
    | '/'
    | '/aluno'
    | '/login'
    | '/privacidade'
    | '/professor'
    | '/recuperar-senha'
    | '/termos'
    | '/aluno/faltas'
    | '/aluno/horarios'
    | '/aluno/notas'
    | '/aluno/notificacoes'
    | '/aluno/propinas'
    | '/aluno/ranking'
    | '/aluno/trocar-senha'
    | '/professor/horario'
    | '/professor/lancar-notas'
    | '/professor/notas'
    | '/professor/perfil'
    | '/professor/turmas'
    | '/aluno/'
    | '/professor/'
    | '/professor/turmas/$turmaId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlunoRoute: typeof AlunoRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ProfessorRoute: typeof ProfessorRouteWithChildren
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  TermosRoute: typeof TermosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno': {
      id: '/aluno'
      path: '/aluno'
      fullPath: '/aluno'
      preLoaderRoute: typeof AlunoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professor': {
      id: '/professor'
      path: '/professor'
      fullPath: '/professor'
      preLoaderRoute: typeof ProfessorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno/': {
      id: '/aluno/'
      path: '/'
      fullPath: '/aluno/'
      preLoaderRoute: typeof AlunoIndexRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/faltas': {
      id: '/aluno/faltas'
      path: '/faltas'
      fullPath: '/aluno/faltas'
      preLoaderRoute: typeof AlunoFaltasRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/horarios': {
      id: '/aluno/horarios'
      path: '/horarios'
      fullPath: '/aluno/horarios'
      preLoaderRoute: typeof AlunoHorariosRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/notas': {
      id: '/aluno/notas'
      path: '/notas'
      fullPath: '/aluno/notas'
      preLoaderRoute: typeof AlunoNotasRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/notificacoes': {
      id: '/aluno/notificacoes'
      path: '/notificacoes'
      fullPath: '/aluno/notificacoes'
      preLoaderRoute: typeof AlunoNotificacoesRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/propinas': {
      id: '/aluno/propinas'
      path: '/propinas'
      fullPath: '/aluno/propinas'
      preLoaderRoute: typeof AlunoPropinasRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/ranking': {
      id: '/aluno/ranking'
      path: '/ranking'
      fullPath: '/aluno/ranking'
      preLoaderRoute: typeof AlunoRankingRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/trocar-senha': {
      id: '/aluno/trocar-senha'
      path: '/trocar-senha'
      fullPath: '/aluno/trocar-senha'
      preLoaderRoute: typeof AlunoTrocarSenhaRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/professor/': {
      id: '/professor/'
      path: '/'
      fullPath: '/professor/'
      preLoaderRoute: typeof ProfessorIndexRouteImport
      parentRoute: typeof ProfessorRoute
    }
    '/professor/horario': {
      id: '/professor/horario'
      path: '/horario'
      fullPath: '/professor/horario'
      preLoaderRoute: typeof ProfessorHorarioRouteImport
      parentRoute: typeof ProfessorRoute
    }
    '/professor/lancar-notas': {
      id: '/professor/lancar-notas'
      path: '/lancar-notas'
      fullPath: '/professor/lancar-notas'
      preLoaderRoute: typeof ProfessorLancarNotasRouteImport
      parentRoute: typeof ProfessorRoute
    }
    '/professor/notas': {
      id: '/professor/notas'
      path: '/notas'
      fullPath: '/professor/notas'
      preLoaderRoute: typeof ProfessorNotasRouteImport
      parentRoute: typeof ProfessorRoute
    }
    '/professor/perfil': {
      id: '/professor/perfil'
      path: '/perfil'
      fullPath: '/professor/perfil'
      preLoaderRoute: typeof ProfessorPerfilRouteImport
      parentRoute: typeof ProfessorRoute
    }
    '/professor/turmas': {
      id: '/professor/turmas'
      path: '/turmas'
      fullPath: '/professor/turmas'
      preLoaderRoute: typeof ProfessorTurmasRouteImport
      parentRoute: typeof ProfessorRoute
    }
    '/professor/turmas/$turmaId': {
      id: '/professor/turmas/$turmaId'
      path: '/$turmaId'
      fullPath: '/professor/turmas/$turmaId'
      preLoaderRoute: typeof ProfessorTurmasTurmaIdRouteImport
      parentRoute: typeof ProfessorTurmasRoute
    }
  }
}

interface AlunoRouteChildren {
  AlunoFaltasRoute: typeof AlunoFaltasRoute
  AlunoHorariosRoute: typeof AlunoHorariosRoute
  AlunoNotasRoute: typeof AlunoNotasRoute
  AlunoNotificacoesRoute: typeof AlunoNotificacoesRoute
  AlunoPropinasRoute: typeof AlunoPropinasRoute
  AlunoRankingRoute: typeof AlunoRankingRoute
  AlunoTrocarSenhaRoute: typeof AlunoTrocarSenhaRoute
  AlunoIndexRoute: typeof AlunoIndexRoute
}

const AlunoRouteChildren: AlunoRouteChildren = {
  AlunoFaltasRoute: AlunoFaltasRoute,
  AlunoHorariosRoute: AlunoHorariosRoute,
  AlunoNotasRoute: AlunoNotasRoute,
  AlunoNotificacoesRoute: AlunoNotificacoesRoute,
  AlunoPropinasRoute: AlunoPropinasRoute,
  AlunoRankingRoute: AlunoRankingRoute,
  AlunoTrocarSenhaRoute: AlunoTrocarSenhaRoute,
  AlunoIndexRoute: AlunoIndexRoute,
}

const AlunoRouteWithChildren = AlunoRoute._addFileChildren(AlunoRouteChildren)

interface ProfessorTurmasRouteChildren {
  ProfessorTurmasTurmaIdRoute: typeof ProfessorTurmasTurmaIdRoute
}

const ProfessorTurmasRouteChildren: ProfessorTurmasRouteChildren = {
  ProfessorTurmasTurmaIdRoute: ProfessorTurmasTurmaIdRoute,
}

const ProfessorTurmasRouteWithChildren = ProfessorTurmasRoute._addFileChildren(
  ProfessorTurmasRouteChildren,
)

interface ProfessorRouteChildren {
  ProfessorHorarioRoute: typeof ProfessorHorarioRoute
  ProfessorLancarNotasRoute: typeof ProfessorLancarNotasRoute
  ProfessorNotasRoute: typeof ProfessorNotasRoute
  ProfessorPerfilRoute: typeof ProfessorPerfilRoute
  ProfessorTurmasRoute: typeof ProfessorTurmasRouteWithChildren
  ProfessorIndexRoute: typeof ProfessorIndexRoute
}

const ProfessorRouteChildren: ProfessorRouteChildren = {
  ProfessorHorarioRoute: ProfessorHorarioRoute,
  ProfessorLancarNotasRoute: ProfessorLancarNotasRoute,
  ProfessorNotasRoute: ProfessorNotasRoute,
  ProfessorPerfilRoute: ProfessorPerfilRoute,
  ProfessorTurmasRoute: ProfessorTurmasRouteWithChildren,
  ProfessorIndexRoute: ProfessorIndexRoute,
}

const ProfessorRouteWithChildren = ProfessorRoute._addFileChildren(
  ProfessorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlunoRoute: AlunoRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ProfessorRoute: ProfessorRouteWithChildren,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  TermosRoute: TermosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
